# Generated by Codex on 2026-04-14

import random

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_usernames_and_personal_spaces(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Space = apps.get_model("accounts", "Space")

    used = set(User.objects.exclude(username__isnull=True).exclude(username="").values_list("username", flat=True))
    for user in User.objects.all():
        changed = False
        if not user.username:
            candidate = None
            while not candidate or candidate in used:
                candidate = f"user{random.randint(100000, 999999)}"
            user.username = candidate
            used.add(candidate)
            changed = True
        if not user.display_name:
            user.display_name = user.username
            changed = True
        if changed:
            user.save(update_fields=["username", "display_name"])

    Space.objects.filter(title="شخصی").update(kind="personal")


def migrate_legacy_images_to_attachments(apps, schema_editor):
    Message = apps.get_model("accounts", "Message")
    MessageAttachment = apps.get_model("accounts", "MessageAttachment")
    for message in Message.objects.exclude(image="").exclude(image__isnull=True):
        MessageAttachment.objects.create(
            id=uuid.uuid4(),
            message=message,
            file=message.image,
            kind="image",
            mime_type="",
            original_name=(str(message.image).split("/")[-1] if message.image else ""),
            sort_order=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="kind",
            field=models.CharField(
                choices=[("personal", "Personal"), ("space", "Space")],
                default="space",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="entries/%Y/%m/%d/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("file", "File"),
                        ],
                        default="file",
                        max_length=16,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=120)),
                ("original_name", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="accounts.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_attachments",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.RunPython(backfill_usernames_and_personal_spaces, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.RunPython(migrate_legacy_images_to_attachments, migrations.RunPython.noop),
    ]
