# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_entries_and_attachments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("music", "Music"),
                    ("voice", "Voice"),
                    ("document", "Document"),
                    ("file", "File"),
                ],
                default="file",
                max_length=16,
            ),
        ),
        migrations.RemoveField(
            model_name="messageattachment",
            name="duration_ms",
        ),
        migrations.RemoveField(
            model_name="messageattachment",
            name="height",
        ),
        migrations.RemoveField(
            model_name="messageattachment",
            name="mime_type",
        ),
        migrations.RemoveField(
            model_name="messageattachment",
            name="size",
        ),
        migrations.RemoveField(
            model_name="messageattachment",
            name="width",
        ),
    ]
